name: generators
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build_config: ^1.0.0


  build:
  source_gen:
  annotations:
    path: ../annotations/

dev_dependencies:
  build_runner:
  build_test:
  test: ^1.0.0

